###############################################################################
# Bazel now uses Bzlmod by default to manage external dependencies.
# Please consider migrating your external dependencies from WORKSPACE to MODULE.bazel.
#
# For more details, please check https://github.com/bazelbuild/bazel/issues/18958
###############################################################################

MODULE_NAME = "the8thwall"

module(
    name = MODULE_NAME,
    compatibility_level = 1,
    version = "1.0",
)

workspace_env = use_repo_rule("//bzl/crosstool:workspace-env.bzl", "workspace_env")

workspace_env(
    name = "workspace-env",
    workspace_name = MODULE_NAME,
)

bazel_dep(name = "platforms", repo_name = "platforms", version = "0.0.11")

single_version_override(
    module_name = "platforms",
    version = "0.0.11",
)

bazel_dep(name = "rules_foreign_cc", repo_name = "rules_foreign_cc", version = "0.9.0")

single_version_override(
    module_name = "rules_foreign_cc",
    version = "0.9.0",
)

bazel_dep(name = "abseil-cpp", repo_name = "com_google_absl", version = "20230802.0.bcr.1")

# lts 20230802.2, patch: adds MODULE.bazel file to abseil-cpp
git_override(
    commit = "929c17cf481222c35ff1652498994871120e832a",
    module_name = "abseil-cpp",
    patches = [
        "//third_party/abseil-cpp:module_dot_bazel.patch",
    ],
    remote = "https://github.com/abseil/abseil-cpp.git",
)

bazel_dep(name = "rules_java", repo_name = "rules_java", version = "7.6.1")
bazel_dep(name = "rules_apple", repo_name = "build_bazel_rules_apple", version = "3.1.1")
bazel_dep(name = "zlib", repo_name = "zlib", version = "1.3")
bazel_dep(name = "curl", version = "8.8.0")
bazel_dep(name = "rules_android", repo_name = "build_bazel_rules_android", version = "0.1.1")

git_override(
    commit = "04f42ceca40f73e2978b50e93806c2a18c1281fc",
    module_name = "zlib",
    patch_strip = 1,
    patches = [
        "//third_party/zlib:zlib.git_override_bzlmod.patch",
    ],
    remote = "https://github.com/madler/zlib.git",
)

bazel_dep(name = "protobuf", repo_name = "com_google_protobuf", version = "25.3-nia")

archive_override(
    integrity = "sha256-Z0r7LQ2q8maFm0+o+fHAUdusVoAKYh37SNIwKEKWC/4=",
    module_name = "protobuf",
    strip_prefix = "protobuf-25.3-nia-v0.3",
    urls = ["https://huggingface.co/datasets/8thWall/bazel-dependencies/resolve/main/protobuf/protobuf-25.3-nia-v0.3.tar"],
)

bazel_dep(name = "org_tensorflow", version = "2.11.0")

archive_override(
    integrity = "sha256-3PONtok5asOuhGsGBjmgsPiFiazWH7kQDvMLEB1SkXI=",
    module_name = "org_tensorflow",
    patches = ["//bzl/thirdpartybuild/tensorflow:tensorflow.patch"],
    strip_prefix = "tensorflow-v2.11.0-p8",
    urls = ["https://huggingface.co/datasets/8thWall/bazel-dependencies/resolve/main/tensorflow/tensorflow-v2.11.0-p8.tar"],
)

archive_override(
    integrity = "sha256-zO6ZKLHkkcrbbXM8iHtUHLP1YBqvrJR3sNFDqN5imWw=",
    module_name = "cpuinfo",
    patch_strip = 1,
    patches = ["//bzl/thirdpartybuild/tensorflow:cpuinfo.patch"],
    strip_prefix = "cpuinfo-8ec7bd91ad0470e61cf38f618cc1f270dede599c",
    urls = ["https://github.com/pytorch/cpuinfo/archive/8ec7bd91ad0470e61cf38f618cc1f270dede599c.zip"],
)

archive_override(
    integrity = "sha256-GDks8HNuHWLsu41pXDFJa2UHhZ6MdVQdetC6CS3FIRU=",
    module_name = "farmhash",
    patches = ["//bzl/thirdpartybuild/tensorflow:farmhash.patch"],
    strip_prefix = "farmhash-0d859a811870d10f53a594927d0d0b97573ad06d",
    urls = ["https://github.com/google/farmhash/archive/0d859a811870d10f53a594927d0d0b97573ad06d.tar.gz"],
)

archive_override(
    integrity = "sha256-X02rwq4h4fU3Ql1YpJzcocSeoR2w1iceKksn6Wl1SOs=",
    module_name = "fft2d",
    patches = ["//bzl/thirdpartybuild/tensorflow:fft2d.patch"],
    strip_prefix = "OouraFFT-1.0",
    urls = ["https://github.com/petewarden/OouraFFT/archive/v1.0.tar.gz"],
)

archive_override(
    integrity = "sha256-Uit6gtkg69DEQIpTZYZqQLgdHA1gsjaQEdMVzKA8ZHY=",
    module_name = "gemmlowp",
    patches = ["//bzl/thirdpartybuild/tensorflow:gemmlowp.patch"],
    strip_prefix = "gemmlowp-e844ffd17118c1e17d94e1ba4354c075a4577b88",
    urls = ["https://github.com/google/gemmlowp/archive/e844ffd17118c1e17d94e1ba4354c075a4577b88.zip"],
)

archive_override(
    integrity = "sha256-3Wv0AyIwPPiYLzQOQTk5fI+jUP9pHVJUWZyyHgE4/GU=",
    module_name = "ruy",
    patch_strip = 1,
    patches = ["//bzl/thirdpartybuild/tensorflow:ruy.patch"],
    strip_prefix = "ruy-841ea4172ba904fe3536789497f9565f2ef64129",
    urls = ["https://github.com/google/ruy/archive/841ea4172ba904fe3536789497f9565f2ef64129.zip"],
)

archive_override(
    integrity = "sha256-eharDXZ9n4gZlz2+odxF5OCCNviatwLZbzif3HjFhVw=",
    module_name = "xnnpack",
    patch_strip = 1,
    patches = ["//bzl/thirdpartybuild/tensorflow:xnnpack.patch"],
    strip_prefix = "XNNPACK-e8f74a9763aa36559980a0c2f37f587794995622",
    urls = ["https://github.com/google/XNNPACK/archive/e8f74a9763aa36559980a0c2f37f587794995622.zip"],
)

single_version_override(
    module_name = "fp16",
    patch_strip = 1,
    patches = ["//bzl/thirdpartybuild/tensorflow:fp16.patch"],
)

single_version_override(
    module_name = "eigen",
    patch_strip = 1,
    patches = ["//bzl/thirdpartybuild/tensorflow:eigen.patch"],
    version = "3.4.0.bcr.1.1",
)

single_version_override(
    module_name = "flatbuffers",
    patch_strip = 1,
    patches = ["//bzl/thirdpartybuild/tensorflow:flatbuffers.patch"],
    version = "24.3.7",
)

single_version_override(
    module_name = "pthreadpool",
    patch_strip = 1,
    patches = ["//bzl/thirdpartybuild/tensorflow:pthreadpool.patch"],
)

bazel_dep(name = "llvm-project", version = "17.0.3")

# Hedron's Compile Commands Extractor for Bazel
# https://github.com/hedronvision/bazel-compile-commands-extractor
# The license for this is generally permissive, but requires any publicly published changes to be pushed back to the main repo:
# https://github.com/hedronvision/bazel-compile-commands-extractor/blob/main/LICENSE.md
bazel_dep(name = "hedron_compile_commands", dev_dependency = True)

git_override(
    commit = "1e08f8e0507b6b6b1f4416a9a22cf5c28beaba93",
    module_name = "hedron_compile_commands",
    remote = "https://github.com/hedronvision/bazel-compile-commands-extractor.git",
    # Replace the commit hash (above) with the latest (https://github.com/hedronvision/bazel-compile-commands-extractor/commits/main).
)

bazel_dep(name = "aspect_bazel_lib", version = "2.7.9")

####################### Rules Oci (Docker image rules) #######################

bazel_dep(name = "rules_oci", version = "2.0.0-beta1")
bazel_dep(name = "container_structure_test", version = "1.19.1")

oci = use_extension("@rules_oci//oci:extensions.bzl", "oci")

oci.pull(
    name = "distroless_base",
    digest = "sha256:ccaef5ee2f1850270d453fdf700a5392534f8d1a8ca2acda391fbb6a06b81c86",
    image = "gcr.io/distroless/base:nonroot",
    platforms = [
        "linux/amd64",
        "linux/arm64",
    ],
)

use_repo(oci, "distroless_base", "distroless_base_linux_amd64", "distroless_base_linux_arm64")

bazel_dep(name = "bazel_skylib", version = "1.7.1")

# Required to fix com_google_protobuf_javalite support
bazel_dep(name = "grpc-java", version = "1.64.0")
bazel_dep(name = "grpc", repo_name = "com_github_grpc_grpc", version = "1.56.3.bcr.1")

http_archive = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

local_repository = use_repo_rule("@bazel_tools//tools/build_defs/repo:local.bzl", "local_repository")

local_repository(
    name = "remote_coverage_tools",
    path = "third_party/remote_coverage_tools",
)

http_archive(
    name = "vulkan_headers",
    build_file = "//bzl/thirdpartybuild:vulkan-headers.BUILD",
    sha256 = "45a8c99f867a686b85bbb6fa460dad41840ecfa1ca111a29f044387f47308dce",
    strip_prefix = "Vulkan-Headers-1.3.296",
    url = "https://github.com/KhronosGroup/Vulkan-Headers/archive/refs/tags/v1.3.296.zip",
)

http_archive(
    name = "com_google_benchmark",
    build_file = "//bzl/thirdpartybuild:benchmark.BUILD",
    sha256 = "3aff99169fa8bdee356eaa1f691e835a6e57b1efeadb8a0f9f228531158246ac",
    strip_prefix = "benchmark-1.7.0",
    url = "https://github.com/google/benchmark/archive/refs/tags/v1.7.0.tar.gz",
)

http_archive(
    name = "node-addon-api",
    build_file = "//bzl/thirdpartybuild:node-addon-api.BUILD",
    sha256 = "10223967fb13567b271639b530c6b13276bced48b57eea9d7c3e172f72cfee92",
    strip_prefix = "node-addon-api-7.0.0",
    url = "https://github.com/nodejs/node-addon-api/archive/refs/tags/v7.0.0.zip",
)

http_archive(
    name = "org_brotli",
    sha256 = "84a9a68ada813a59db94d83ea10c54155f1d34399baf377842ff3ab9b3b3256e",
    strip_prefix = "brotli-3914999fcc1fda92e750ef9190aa6db9bf7bdb07",
    url = "https://github.com/google/brotli/archive/3914999fcc1fda92e750ef9190aa6db9bf7bdb07.zip",
)

http_archive(
    name = "eigen3",
    build_file = "//bzl/thirdpartybuild:eigen3.BUILD",
    patches = [
        "//third_party/eigen3:TriangularSolver.h.patch",
    ],
    sha256 = "8586084f71f9bde545ee7fa6d00288b264a2b7ac3607b974e54d13e7162c1c72",
    strip_prefix = "eigen-3.4.0",
    url = "https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.tar.gz",
)

http_archive(
    name = "giflib",
    build_file = "//bzl/thirdpartybuild:giflib.BUILD",
    sha256 = "be7ffbd057cadebe2aa144542fd90c6838c6a083b5e8a9048b8ee3b66b29d5fb",
    strip_prefix = "giflib-5.2.2",
    url = "https://huggingface.co/datasets/8thWall/bazel-dependencies/resolve/main/giflib/giflib-5.2.2.tar.gz",
)

http_archive(
    name = "cli11",
    build_file = "//bzl/thirdpartybuild:cli11.BUILD",
    sha256 = "562c4be7507dc6fb4997ecd648bf935d84efe17b54715fa5cfbddac05279f668",
    strip_prefix = "CLI11-2.3.2",
    url = "https://github.com/CLIUtils/CLI11/archive/refs/tags/v2.3.2.zip",
)

http_archive(
    name = "mono-macosx",
    build_file = "//bzl/thirdpartybuild:mono.BUILD",
    sha256 = "8d569e7dc07207a3e008b3756bb1f10a93a720e325dcf559e6e0e5a449b94421",
    strip_prefix = "Mono.framework/Versions/6.12.0",
    url = "https://huggingface.co/datasets/8thWall/bazel-dependencies/resolve/main/mono/Mono.framework-6.12.0-macosx-x86_64.tar",
)

http_archive(
    name = "zstd",
    build_file = "//bzl/thirdpartybuild:zstd.BUILD",
    sha256 = "30f35f71c1203369dc979ecde0400ffea93c27391bfd2ac5a9715d2173d92ff7",
    strip_prefix = "zstd-1.5.6",
    url = "https://github.com/facebook/zstd/archive/refs/tags/v1.5.6.tar.gz",
)

http_archive(
    name = "spz",
    build_file = "//bzl/thirdpartybuild:spz.BUILD",
    sha256 = "266c144fddb87f428495bbe1e44748fc3f1e5bfaa9e354a5d0d0284c4f8946cc",
    strip_prefix = "spz-3.0.0",
    url = "https://github.com/nianticlabs/spz/archive/refs/tags/v3.0.0.tar.gz",
)

http_archive(
    name = "com_google_googletest",
    patch_args = ["-p1"],
    patches = [
        "//third_party/googletest:googletest-1.14.0-wasm_support.patch",
    ],
    sha256 = "8ad598c73ad796e0d8280b082cebd82a630d73e73cd3c70057938a6501bba5d7",
    strip_prefix = "googletest-1.14.0",
    urls = [
        "https://github.com/google/googletest/archive/refs/tags/v1.14.0.tar.gz",
    ],
)

git_repository = use_repo_rule("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "miniaudio",
    build_file = "//bzl/thirdpartybuild:miniaudio.BUILD",
    commit = "4a5b74bef029b3592c54b6048650ee5f972c1a48",  # v0.11.21
    remote = "https://github.com/mackron/miniaudio.git",
    shallow_since = "1700011380 +1000",
)

git_repository(
    name = "com_github_gflags_gflags",
    commit = "986e8eed00ded8168ef4eaa6f925dc6be50b40fa",
    remote = "https://github.com/gflags/gflags",
    shallow_since = "1641684284 +0000",
)

git_repository(
    name = "fmt",
    commit = "a33701196adfad74917046096bf5a2aa0ab0bb50",
    patch_cmds = [
        "mv support/bazel/.bazelrc .bazelrc",
        "mv support/bazel/.bazelversion .bazelversion",
        "mv support/bazel/BUILD.bazel BUILD.bazel",
        "mv support/bazel/WORKSPACE.bazel WORKSPACE.bazel",
    ],
    patch_cmds_win = [
        "Move-Item -Path support/bazel/.bazelrc -Destination .bazelrc",
        "Move-Item -Path support/bazel/.bazelversion -Destination .bazelversion",
        "Move-Item -Path support/bazel/BUILD.bazel -Destination BUILD.bazel",
        "Move-Item -Path support/bazel/WORKSPACE.bazel -Destination WORKSPACE.bazel",
    ],
    remote = "https://github.com/fmtlib/fmt",
)

new_git_repository = use_repo_rule("@bazel_tools//tools/build_defs/repo:git.bzl", "new_git_repository")

new_git_repository(
    name = "flecs",
    build_file = "//bzl/thirdpartybuild:flecs.BUILD",
    commit = "bf9ec9f8aecd987bee63e6c0af4164c7be14b42f",  # https://github.com/SanderMertens/flecs/releases/tag/v4.0.2
    remote = "https://github.com/SanderMertens/flecs.git",
    shallow_since = "1727187792 -0700",
)

new_git_repository(
    name = "joltphysics",
    build_file = "//bzl/thirdpartybuild:joltphysics.BUILD",
    commit = "0373ec0dd762e4bc2f6acdb08371ee84fa23c6db",  #  v5.3.0
    remote = "https://github.com/jrouwe/JoltPhysics.git",
    shallow_since = "1742071981 +0100",
)

new_git_repository(
    name = "sophus",
    build_file = "//bzl/thirdpartybuild:sophus.BUILD",
    commit = "de0f8d3d92bf776271e16de56d1803940ebccab9",  # 1.22.10
    remote = "https://github.com/strasdat/Sophus.git",
    shallow_since = "1675598033 -0800",
)

new_git_repository(
    name = "json",
    build_file = "//bzl/thirdpartybuild:json.BUILD",
    commit = "4f8fba14066156b73f1189a2b8bd568bde5284c5",
    remote = "https://github.com/nlohmann/json.git",
    shallow_since = "1641188409 +0100",
)

new_git_repository(
    name = "spirv_cross",
    build_file = "//bzl/thirdpartybuild:spirv-cross.BUILD",
    commit = "61c603f3baa5270e04bcfb6acf83c654e3c57679",
    remote = "https://github.com/KhronosGroup/SPIRV-Cross.git",
    shallow_since = "1660048855 +0200",
)

new_git_repository(
    name = "capnproto_python",
    build_file = "//bzl/thirdpartybuild:capnproto_python.BUILD",
    commit = "b3ab9ab2a6eeb493ee2fe1d61a09a933828145c7",
    remote = "https://github.com/jparyani/pycapnp.git",
    shallow_since = "1501210794 -0700",
)

new_git_repository(
    name = "kissfftlib",
    build_file = "//bzl/thirdpartybuild:kissfft.BUILD",
    commit = "8f47a67f595a6641c566087bf5277034be64f24d",
    remote = "https://github.com/mborgerding/kissfft.git",
    shallow_since = "1612920557 -0500",
)

new_git_repository(
    name = "draco",
    build_file = "//bzl/thirdpartybuild:draco.BUILD",
    commit = "bd1e8de7dd0596c2cbe5929cbe1f5d2257cd33db",
    remote = "https://github.com/google/draco.git",
    shallow_since = "1645135565 -0800",
)

new_git_repository(
    name = "libmp4v2",
    build_file = "//bzl/thirdpartybuild:libmp4v2.BUILD",
    commit = "b0e3019fb301362dedd376ba3f4fb7263b277c11",
    remote = "https://github.com/8thwall/libmp4v2",
    shallow_since = "1589395781 -0700",
)

new_git_repository(
    name = "libjpegturbo",
    build_file = "//bzl/thirdpartybuild:libjpegturbo.BUILD",
    commit = "9171fd4bdef0f3aecba61413b858b1766bbad8d5",
    patch_args = ["-p1"],
    patches = [
        "//third_party/libjpegturbo:turbojpeg.c.patch",
    ],
    remote = "https://github.com/libjpeg-turbo/libjpeg-turbo.git",
    shallow_since = "1651080868 -0500",
)

new_git_repository(
    name = "capnproto",
    build_file = "//bzl/thirdpartybuild:capnproto.BUILD",
    commit = "c3c2655f6d6efeb93ae6b3ea718eecd00b72f5d0",
    remote = "https://github.com/8thwall/capnproto.git",
    shallow_since = "1699486035 -0800",
)

new_git_repository(
    name = "capnproto_java",
    build_file = "//bzl/thirdpartybuild:capnproto_java.BUILD",
    commit = "be364f41c66b8c41484e0cb5bc25f726613cc04a",
    remote = "https://github.com/dwrensha/capnproto-java",
    shallow_since = "1488309561 -0500",
)

new_git_repository(
    name = "ceres",
    build_file = "//bzl/thirdpartybuild:ceres.BUILD",
    commit = "2b32b321242b32f6364108694e0069f87e56326c",
    remote = "https://github.com/ceres-solver/ceres-solver",
    shallow_since = "1613587123 +0000",
)

new_git_repository(
    name = "ceres2",
    build_file = "//bzl/thirdpartybuild:ceres2.BUILD",
    commit = "fd6197ce0ef5794bba455fe6f907dcdabcf624eb",
    remote = "https://github.com/ceres-solver/ceres-solver",
    shallow_since = "1686411471 +0200",
)

new_git_repository(
    name = "png",
    build_file = "//bzl/thirdpartybuild:png.BUILD",
    commit = "eddf9023206dc40974c26f589ee2ad63a4227a1e",
    remote = "https://github.com/glennrp/libpng.git",
    shallow_since = "1543674960 -0500",
)

new_git_repository(
    name = "tinygltf",
    build_file = "//bzl/thirdpartybuild:tinygltf.BUILD",
    commit = "e0b393c6958c0a7cbe134a240fad7915aae53db3",
    remote = "https://github.com/syoyo/tinygltf.git",
    shallow_since = "1694518115 +0900",
)

new_git_repository(
    name = "zlib-chromium",
    build_file = "//bzl/thirdpartybuild:zlib-chromium.BUILD",
    commit = "f5fd0ad2663e239a31184ad4c9919991dda16f46",
    remote = "https://chromium.googlesource.com/chromium/src/third_party/zlib",
    shallow_since = "1691776355 -0700",
)

new_git_repository(
    name = "libevent",
    build_file = "//third_party/libevent:libevent.BUILD",
    commit = "e7ff4ef2b4fc950a765008c18e74281cdb5e7668",
    remote = "https://github.com/libevent/libevent",
    shallow_since = "1485387435 +0300",
)

http_archive(
    name = "org_freetype_freetype2",
    build_file = "//bzl/thirdpartybuild:freetype2.BUILD",
    sha256 = "e09aa914e4f7a5d723ac381420949c55c0b90b15744adce5d1406046022186ab",
    strip_prefix = "freetype-2.10.2",
    urls = [
        "http://download.savannah.gnu.org/releases/freetype/freetype-2.10.2.tar.gz",
        "https://sourceforge.net/projects/freetype/files/freetype2/2.10.2/freetype-2.10.2.tar.gz",
    ],
)

http_archive(
    name = "mdnsresponder",
    build_file = "//bzl/thirdpartybuild:mdnsresponder.BUILD",
    patches = ["//third_party/mdnsresponder:dllmain.c.patch"],
    sha256 = "75d66beadae8a64a5d30986afe45259b73b03bc6f4cb1b64acca7079cf11e056",
    strip_prefix = "mDNSResponder-mDNSResponder-765.50.9",
    url = "https://opensource.apple.com/tarballs/mDNSResponder/mDNSResponder-765.50.9.tar.gz",
)

new_git_repository(
    name = "libyuv",
    build_file = "//bzl/thirdpartybuild:libyuv.BUILD",
    commit = "de71c67e53d79190b5b7cc760ade9027855dd945",
    remote = "https://chromium.googlesource.com/libyuv/libyuv",
    shallow_since = "1651045085 +0000",
)

new_git_repository(
    name = "xcpretty",
    build_file_content = """
filegroup(
    name = 'xcpretty',
    srcs = glob(
        include=['**'],
        exclude=['features/assets/**'],
    ),
    visibility = ["//visibility:public"],
)""",
    commit = "fb3afc6f4495fa89c2dcb351b274eacb74595285",
    remote = "https://github.com/supermarin/xcpretty.git",
    shallow_since = "1476195465 -0700",
)

new_git_repository(
    name = "opencv",
    build_file = "//bzl/thirdpartybuild:opencv.BUILD",
    commit = "70bbf17b133496bd7d54d034b0f94bd869e0e810",
    remote = "https://github.com/opencv/opencv",
    shallow_since = "1482497684 +0300",
)

new_git_repository(
    name = "libgit2",
    build_file = "//bzl/thirdpartybuild:libgit2.BUILD",
    commit = "78fde8cde56492d464575e3bf289056c8289cec8",
    remote = "https://github.com/8thwall/libgit2.git",
    shallow_since = "1731372343 -0800",
)

new_git_repository(
    name = "androidmdnsresponder",
    build_file = "//bzl/thirdpartybuild:androidmdnsresponder.BUILD",
    commit = "85d33e8312069bc5b3d0e307589e0919922e687c",
    remote = "https://android.googlesource.com/platform/external/mdnsresponder",
    shallow_since = "1507706791 +0000",
)

new_git_repository(
    name = "opus",
    build_file = "//bzl/thirdpartybuild:opus.BUILD",
    commit = "d633f523e36e3b6d01cc6d57386458d770d618be",
    remote = "https://github.com/xiph/opus.git",
    shallow_since = "1611443214 -0800",
)

new_git_repository(
    name = "libwebm",
    build_file = "//bzl/thirdpartybuild:libwebm.BUILD",
    commit = "485fb67b324aec5298765e899dc054459d3946e5",
    remote = "https://chromium.googlesource.com/webm/libwebm",
    shallow_since = "1606261220 +0000",
)

new_git_repository(
    name = "libvpx",
    build_file = "//bzl/thirdpartybuild:libvpx.BUILD",
    commit = "0d8354669ac525a27c78bc8c761e98e0f8c3905c",
    patches = ["//third_party/libvpx:config.patch"],
    remote = "https://chromium.googlesource.com/webm/libvpx",
    shallow_since = "1612419145 -0800",
)

new_git_repository(
    name = "openh264",
    build_file = "//bzl/thirdpartybuild:openh264.BUILD",
    commit = "22a46624f3b5c88e017ae5fb78f7a66e06bfccb9",
    remote = "https://github.com/8thwall/openh264",
    shallow_since = "1612314198 -0800",
)

new_git_repository(
    name = "fdkaac",
    build_file = "//bzl/thirdpartybuild:fdkaac.BUILD",
    commit = "573e93e4d0d08127dd3b2297a0ce52221527d90a",
    patches = [
        "//third_party/fdk-aac:FDK_archdef.h.patch",
        "//third_party/fdk-aac:FDK_lpp_tran.cpp.patch",
    ],
    remote = "https://github.com/mstorsjo/fdk-aac",
    shallow_since = "1629788404 +0300",
)

http_file = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")

http_file(
    name = "android-bundle-tool",
    sha256 = "45881ead13388872d82c4255b195488b7fc33f2cac5a9a977b0afc5e92367592",
    url = "https://github.com/google/bundletool/releases/download/1.17.1/bundletool-all-1.17.1.jar",
)

http_file(
    name = "android-manifest-merger",
    sha256 = "4e06d2f8b545741847495f4cfdd14eb8ccf42eb21241e8be0387759ce074c415",
    url = "https://huggingface.co/datasets/8thWall/bazel-dependencies/resolve/main/android-manifest-merger/android-manifest-merger-31.5.2.jar",
)

http_jar = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_jar")

http_jar(
    name = "aws-lambda-java-core",
    sha256 = "5212360097b6f64bed1b5d7ad96a80b7d59b41c5e8d4f5f84294d07e045415d4",
    url = "https://huggingface.co/datasets/8thWall/bazel-dependencies/resolve/main/aws-lambda/aws-lambda-java-core-1.2.3.jar",
)

http_jar(
    name = "aws-lambda-java-events",
    sha256 = "3c7246e51a4784bac653d917183ef224d90486ba863ca2d2f81292865c67feb7",
    url = "https://huggingface.co/datasets/8thWall/bazel-dependencies/resolve/main/aws-lambda/aws-lambda-java-events-3.11.1.jar",
)

http_jar(
    name = "aws-lambda-java-log4j2",
    sha256 = "2b7c33b1a8893f96f99c903cc859fecb6d11f979d36f2f5bc92bb1dc032d27cb",
    url = "https://huggingface.co/datasets/8thWall/bazel-dependencies/resolve/main/aws-lambda/aws-lambda-java-log4j2-1.5.1.jar",
)

http_jar(
    name = "joda-time",
    sha256 = "3ff52823754872b7df723920fe9c95b97feed151d4eeeedfddf56dd7694b8a3a",
    url = "https://huggingface.co/datasets/8thWall/bazel-dependencies/resolve/main/aws-lambda/joda-time-2.10.8.jar",
)

http_jar(
    name = "log4j-api",
    sha256 = "e0f13acee7e257846004994340ebb621a9f9113c4c7747f5f52eb65b0ca4abef",
    url = "https://huggingface.co/datasets/8thWall/bazel-dependencies/resolve/main/aws-lambda/log4j-api-2.17.1.jar",
)

http_jar(
    name = "log4j-core",
    sha256 = "192f2778925988ae8b49cfca5aad32caefc847037dde0eedd230683a0de876ff",
    url = "https://huggingface.co/datasets/8thWall/bazel-dependencies/resolve/main/aws-lambda/log4j-core-2.17.1.jar",
)

terrain_service_support = use_repo_rule("//bzl/services:terrain-service.bzl", "terrain_service_support")

terrain_service_support(
    name = "terrain_service_support",
)
