licenses(["permissive"])  # FDK-AAC License

cc_library(
    name = "fdk-aac-arm-src-includes",
    hdrs = glob([
        "libAACdec/src/arm/*.cpp",
        "libFDK/src/arm/*.cpp",
        "libSBRdec/src/arm/*.cpp",
    ]),
)

cc_library(
    name = "fdk-aac",
    srcs = glob([
        "libAACdec/include/*.h",
        "libAACdec/include/*.h",
        "libAACenc/include/*.h",
        "libArithCoding/include/*.h",
        "libDRCdec/include/*.h",
        "libSACdec/include/*.h",
        "libSACenc/include/*.h",
        "libSBRdec/include/*.h",
        "libSBRenc/include/*.h",
        "libMpegTPDec/include/*.h",
        "libMpegTPEnc/include/*.h",
        "libSYS/include/*.h",
        "libFDK/include/*.h",
        "libFDK/include/**/*.h",
        "libPCMutils/include/*.h",
        "libAACdec/src/*.h",
        "libAACdec/src/*.h",
        "libAACdec/src/*.h",
        "libAACenc/src/*.h",
        "libArithCoding/src/*.h",
        "libDRCdec/src/*.h",
        "libSACdec/src/*.h",
        "libSACenc/src/*.h",
        "libSBRdec/src/*.h",
        "libSBRenc/src/*.h",
        "libMpegTPDec/src/*.h",
        "libMpegTPEnc/src/*.h",
        "libSYS/src/*.h",
        "libFDK/src/*.h",
        "libPCMutils/src/*.h",
        "libAACdec/src/*.cpp",
        "libAACdec/src/*.cpp",
        "libAACdec/src/*.cpp",
        "libAACenc/src/*.cpp",
        "libArithCoding/src/*.cpp",
        "libDRCdec/src/*.cpp",
        "libSACdec/src/*.cpp",
        "libSACenc/src/*.cpp",
        "libSBRdec/src/*.cpp",
        "libSBRenc/src/*.cpp",
        "libMpegTPDec/src/*.cpp",
        "libMpegTPEnc/src/*.cpp",
        "libSYS/src/*.cpp",
        "libFDK/src/*.cpp",
        "libPCMutils/src/*.cpp",
    ]),
    hdrs = [
        ":public-headers",
    ],
    copts = [
        "-Wno-unused-variable",
        "-Wno-unused-const-variable",
    ],
    includes = [
        "include",
        "libAACdec/include",
        "libAACenc/include",
        "libArithCoding/include",
        "libDRCdec/include",
        "libFDK/include",
        "libMpegTPDec/include",
        "libMpegTPEnc/include",
        "libPCMutils/include",
        "libSACdec/include",
        "libSACenc/include",
        "libSBRdec/include",
        "libSBRenc/include",
        "libSYS/include",
    ],
    visibility = ["//visibility:public"],
    deps = select({
        "@the8thwall//bzl/conditions:arm-any": [
            ":fdk-aac-arm-src-includes",
        ],
        "//conditions:default": [],
    }),
)

genrule(
    name = "public-headers",
    srcs = [
        "libSYS/include/machine_type.h",
        "libSYS/include/genericStds.h",
        "libSYS/include/FDK_audio.h",
        "libSYS/include/syslib_channelMapDescr.h",
        "libAACenc/include/aacenc_lib.h",
        "libAACdec/include/aacdecoder_lib.h",
    ],
    outs = [
        "include/fdk-aac/machine_type.h",
        "include/fdk-aac/genericStds.h",
        "include/fdk-aac/FDK_audio.h",
        "include/fdk-aac/syslib_channelMapDescr.h",
        "include/fdk-aac/aacenc_lib.h",
        "include/fdk-aac/aacdecoder_lib.h",
    ],
    cmd = "cp $(SRCS) $(@D)/include/fdk-aac/",
    visibility = ["//visibility:private"],
)
